
import connectDB from '@/app/lib/connect';
import Product from '@/models/Products';
import Business from '@/models/Business';
import { NextResponse } from 'next/server';
import { verifyAuth } from '@/app/lib/verifyAuth';


export async function GET(req) {

    const auth = await verifyAuth(req, ["admin"]);

    // If authentication or authorization fails, i
    if (!auth.isValid) {
        return NextResponse.json({
            success: false,
            message: auth.message
        },

            { status: auth.status });
    }

    try {
        await connectDB();

        const rawPendingData = await Product.aggregate([
            // Get all products pending publication
            {
                $match: { status: 'under_review', isActive:true }
            },
            //Join with the business collection to get vendor info
            {
                $lookup: {
                    from: 'businesses',
                    localField: 'businessId',
                    foreignField: '_id',
                    as: 'businessDetails'
                }
            },
            {
                $unwind: {
                    path: '$businessDetails',
                    preserveNullAndEmptyArrays: true
                }
            },
            // Subquery: Go back to products collection to count "under_review" items for THIS business
            {
                $lookup: {
                    from: 'products', // Looking up the same collection
                    let: { bId: '$businessId' }, // Define variable from current product's businessId
                    pipeline: [
                        {
                            $match: {
                                $expr: {
                                    $and: [
                                        { $gt: ["$$bId", null] }, // prevent null business counting
                                        { $eq: ['$businessId', '$$bId'] },     // Match the business
                                        { $eq: ['$status', 'under_review'] }   // Filter only under_review status
                                    ]
                                }
                            }
                        }
                    ],
                    as: 'underReviewItems'
                }
            },

            {
                $sort: { createdAt: -1 }
            }
        ]);

        console.log("RAW PEMDING DATA", rawPendingData);
        // Format the payload 
        const products = rawPendingData.map(item => ({
            id: item._id.toString(),
            productName: item.productName,
            price: item.price,
            slug: item.slug,
            status: item.status,
            discountPrice:item.discountPrice,
            discountPercentage:item.discountPercentage,
            productImages: item.productImages, //|| 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300
            vendorName: item.businessDetails ? item.businessDetails.businessName : 'Independent Vendor',
            // Compute the total array size generated by the custom lookup
            underReviewCount: item.underReviewItems ? item.underReviewItems.length : 0
        }));

        return NextResponse.json(
            {
                success: true,
                products,
            },
            { status: 200 });


    } catch (error) {
        console.error('Error fetching pending products:', error);
        return NextResponse.json(
            {
                success: false,
                message: "Failed to get vendor's pending business",
                error: error.message,
            },
            { status: 500 }
        );
    }
}