import {
  randomInt,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";

import bcrypt from "bcryptjs";

import {
  SignupError,
  normalizeEmail,
  validatePassword,
  hashSecret,
  encryptBvn,
  encryptIdentityNumber,
} from "./signup-validation.js";

const MINUTE = 60 * 1000;

export function createSignupService({
  connect,
  Challenge,
  User,
  Business,
  uploadDocument,
  deleteDocument,
  sendCodeEmail,
}) {
  /**
   * ======================================================
   * SEND VERIFICATION CODE
   * ======================================================
   */
  async function sendCode(rawEmail) {
    const email = normalizeEmail(rawEmail);

    const code = String(
      randomInt(0, 1000000)
    ).padStart(6, "0");

    const codeHash = hashSecret(
      `${email}:${code}`
    );

    await connect();

    /*
     * Check whether a verified user already exists.
     */
    const user = await User.findOne({
      email,
    });

    if (user?.emailVerified) {
      throw new SignupError(
        "This email already has a verified account. Please sign in.",
        409
      );
    }

    const now = new Date();

    /*
     * ------------------------------------------------------
     * Create challenge record if it doesn't exist
     * ------------------------------------------------------
     */
    try {
      await Challenge.updateOne(
        {
          email,
        },
        {
          $setOnInsert: {
            email,

            sendCount: 0,

            windowExpiresAt: new Date(
              now.getTime() +
                60 * MINUTE
            ),

            purgeAt: new Date(
              now.getTime() +
                24 * 60 * MINUTE
            ),
          },
        },
        {
          upsert: true,
        }
      );
    } catch (error) {
      /*
       * Ignore duplicate challenge race.
       *
       * Two requests could attempt to create the same
       * challenge at virtually the same time.
       */
      if (error.code !== 11000) {
        throw error;
      }
    }

    /*
     * ------------------------------------------------------
     * Reset hourly rate-limit window if expired
     * ------------------------------------------------------
     */
    await Challenge.updateOne(
      {
        email,

        windowExpiresAt: {
          $lte: now,
        },
      },
      {
        $set: {
          sendCount: 0,

          windowExpiresAt: new Date(
            now.getTime() +
              60 * MINUTE
          ),
        },
      }
    );

    /*
     * ------------------------------------------------------
     * Generate/save OTP atomically
     * ------------------------------------------------------
     *
     * Maximum:
     * 5 OTP sends per hour.
     *
     * Minimum:
     * 60 seconds between sends.
     */
    const challenge =
      await Challenge.findOneAndUpdate(
        {
          email,

          sendCount: {
            $lt: 5,
          },

          $or: [
            {
              nextSendAt: {
                $lte: now,
              },
            },
            {
              nextSendAt: {
                $exists: false,
              },
            },
          ],
        },
        {
          $inc: {
            sendCount: 1,
          },

          $set: {
            codeHash,

            codeExpiresAt:
              new Date(
                now.getTime() +
                  15 * MINUTE
              ),

            attempts: 0,

            nextSendAt:
              new Date(
                now.getTime() +
                  MINUTE
              ),

            purgeAt:
              new Date(
                now.getTime() +
                  24 * 60 * MINUTE
              ),
          },

          /*
           * A newly generated OTP invalidates any
           * verification proof generated by an older OTP.
           */
          $unset: {
            proofHash: "",
            proofExpiresAt: "",
            usedAt: "",
          },
        },
        {
          returnDocument: "after",
        }
      );

    if (!challenge) {
      throw new SignupError(
        "Please wait before requesting another code. Up to 5 codes are allowed per hour.",
        429
      );
    }

    /*
     * ------------------------------------------------------
     * Send verification email
     * ------------------------------------------------------
     */
    try {
      await sendCodeEmail(
        email,
        code
      );
    } catch (error) {
      /*
       * If email delivery fails, remove the OTP.
       *
       * We deliberately leave the cooldown in place to
       * avoid someone abusing the endpoint to hammer SMTP.
       */
      await Challenge.updateOne(
        {
          email,
          codeHash,
        },
        {
          $unset: {
            codeHash: "",
            codeExpiresAt: "",
          },
        }
      );

      throw new SignupError(
        "The verification email could not be sent. Please try again in a minute.",
        503
      );
    }

    return {
      success: true,

      message:
        "Verification code sent to your email.",

      retryAfter: 60,

      expiresIn: 900,
    };
  }

  /**
   * ======================================================
   * VERIFY EMAIL CODE
   * ======================================================
   *
   * No MongoDB transaction is used here.
   *
   * MongoDB guarantees that an update against a single
   * document is atomic. findOneAndUpdate() therefore gives
   * us the protection needed around the Challenge record.
   */
  async function verifyCode(
    rawEmail,
    code
  ) {
    const email =
      normalizeEmail(rawEmail);

    if (
      typeof code !== "string" ||
      !/^\d{6}$/.test(code)
    ) {
      throw new SignupError(
        "Enter the six-digit verification code.",
        400
      );
    }

    const codeHash =
      hashSecret(
        `${email}:${code}`
      );

    await connect();

    const now = new Date();

    /*
     * ------------------------------------------------------
     * Reserve one OTP attempt atomically
     * ------------------------------------------------------
     */
    const challenge =
      await Challenge.findOneAndUpdate(
        {
          email,

          codeExpiresAt: {
            $gt: now,
          },

          attempts: {
            $lt: 5,
          },

          usedAt: {
            $exists: false,
          },
        },
        {
          $inc: {
            attempts: 1,
          },
        },
        {
          returnDocument: "after",
        }
      );

    if (!challenge) {
      throw new SignupError(
        "The code has expired or reached its attempt limit. Request a new code.",
        400
      );
    }

    /*
     * ------------------------------------------------------
     * Compare OTP hashes
     * ------------------------------------------------------
     *
     * timingSafeEqual helps avoid timing-based comparisons.
     */
    const stored = Buffer.from(
      challenge.codeHash || "",
      "hex"
    );

    const received = Buffer.from(
      codeHash,
      "hex"
    );

    if (
      stored.length !==
        received.length ||
      !timingSafeEqual(
        stored,
        received
      )
    ) {
      throw new SignupError(
        "The verification code is incorrect.",
        400
      );
    }

    /*
     * ------------------------------------------------------
     * Generate signup verification proof
     * ------------------------------------------------------
     *
     * This token is returned to the frontend.
     *
     * We DO NOT save the actual token.
     * Only its hash is stored.
     */
    const verificationToken =
      randomBytes(32).toString(
        "hex"
      );

    const verificationProofHash =
      hashSecret(
        verificationToken
      );

    /*
     * ------------------------------------------------------
     * Atomically attach proof to this OTP challenge
     * ------------------------------------------------------
     */
    const verified =
      await Challenge.findOneAndUpdate(
        {
          _id:
            challenge._id,

          codeHash,

          usedAt: {
            $exists: false,
          },

          codeExpiresAt: {
            $gt: new Date(),
          },
        },
        {
          $set: {
            documentScanCount: 0,
            proofHash:
              verificationProofHash,

            proofExpiresAt:
              new Date(
                Date.now() +
                  60 * MINUTE
              ),
          },
        },
        {
          returnDocument: "after",
        }
      );

    if (!verified) {
      throw new SignupError(
        "The code was replaced or expired. Request a new code.",
        400
      );
    }

    /*
     * ------------------------------------------------------
     * Existing/unverified account compatibility
     * ------------------------------------------------------
     *
     * No session/transaction required.
     */
    await User.updateOne(
      {
        email,

        emailVerified:
          false,
      },
      {
        $set: {
          emailVerified:
            true,
        },
      }
    );

    return {
      success: true,

      verificationToken,

      expiresIn: 3600,

      message:
        "Email verified.",
    };
  }

  /**
   * ======================================================
   * REGISTER SELLER
   * ======================================================
   *
   * IMPORTANT:
   *
   * We are NOT using MongoDB transactions because the
   * current MongoDB deployment is standalone.
   *
   * Instead:
   *
   * 1. Validate verification proof
   * 2. Upload document
   * 3. Atomically consume proof
   * 4. Create User
   * 5. Create Business
   * 6. Roll back manually if anything fails
   */
  async function registerSeller(
    data
  ) {
    const email =
      normalizeEmail(
        data.email
      );

    if (
      !data.verificationToken
    ) {
      throw new SignupError(
        "Email verification is required.",
        403
      );
    }

    const proofHash =
      hashSecret(
        data.verificationToken
      );

    await connect();

    /*
     * ------------------------------------------------------
     * Check whether seller already exists
     * ------------------------------------------------------
     */
    const existing =
      await User.findOne({
        email,
      }).select(
        "+signupProofHash"
      );

    if (existing) {
      /*
       * Handles a client retry after signup actually
       * completed successfully.
       */
      if (
        existing.signupProofHash ===
        proofHash
      ) {
        return {
          success: true,

          message:
            "Registration already submitted.",
        };
      }

      throw new SignupError(
        "An account with this email already exists.",
        409
      );
    }

    /*
     * ------------------------------------------------------
     * Validate email verification proof
     * ------------------------------------------------------
     */
    const proofFilter = {
      email,

      proofHash,

      proofExpiresAt: {
        $gt: new Date(),
      },

      usedAt: {
        $exists: false,
      },
    };

    const proofExists =
      await Challenge.exists(
        proofFilter
      );

    if (!proofExists) {
      throw new SignupError(
        "Email verification has expired. Verify your email again.",
        403
      );
    }

    /*
     * ------------------------------------------------------
     * Validate/hash password
     * ------------------------------------------------------
     */
    const validPassword =
      validatePassword(
        data.password
      );

    const password =
      await bcrypt.hash(
        validPassword,
        12
      );

    /*
     * ------------------------------------------------------
     * Encrypt BVN
     * ------------------------------------------------------
     */
    const bvnEncrypted =
      encryptBvn(
        data.bvn
      );

    const ninEncrypted = data.nin ? encryptIdentityNumber(data.nin) : undefined;
    const abssinEncrypted = encryptIdentityNumber(data.abssin);

    /*
     * ------------------------------------------------------
     * Upload CAC document
     * ------------------------------------------------------
     *
     * Upload happens before consuming the verification
     * token. If upload fails, user can retry normally.
     */
    const document =
      await uploadDocument(
        data.document
      );

    let ninDocument = null;
    const cleanupDocuments = async () => {
      await Promise.all([document, ninDocument].filter(Boolean).map((file) =>
        deleteDocument(file).catch(() => console.error("Signup identity document cleanup failed; review private storage."))
      ));
    };
    let createdUser = null;
    let proofConsumed =
      false;

    try {
      if (data.ninDocument) ninDocument = await uploadDocument({ ...data.ninDocument, purpose: "nin" });
      /*
       * ----------------------------------------------------
       * Consume verification proof atomically
       * ----------------------------------------------------
       *
       * Only ONE request can successfully consume the
       * verification proof.
       */
      const proof =
        await Challenge.findOneAndUpdate(
          {
            email,

            proofHash,

            proofExpiresAt: {
              $gt: new Date(),
            },

            usedAt: {
              $exists: false,
            },
          },
          {
            $set: {
              usedAt:
                new Date(),
            },
          },
          {
            returnDocument:
              "after",
          }
        );

      if (!proof) {
        /*
         * Another request may have completed the signup
         * while this request was uploading the document.
         */
        const winner =
          await User.findOne({
            email,
          }).select(
            "+signupProofHash"
          );

        if (
          winner
            ?.signupProofHash ===
          proofHash
        ) {
          /*
           * Our upload is now unused.
           */
          await cleanupDocuments();

          return {
            success: true,

            message:
              "Registration already submitted.",
          };
        }

        throw new SignupError(
          "Verification was already used or has expired.",
          409
        );
      }

      proofConsumed = true;

      /*
       * ----------------------------------------------------
       * Create user
       * ----------------------------------------------------
       */
      createdUser =
        await User.create({
          email,

          password,

          role:
            "vendor",

          emailVerified:
            true,

          phoneNumber:
            `${data.business.countryCode}${data.business.phoneNumber.replace(
              /^0/,
              ""
            )}`,

          onBoardingStatus:
            "completed",

          verificationStatus:
            "pending",

          verificationMethod:
            "bvn",

          acceptedTermsAt:
            new Date(),

          /*
           * Used to safely identify duplicate/retried
           * registration requests.
           */
          signupProofHash:
            proofHash,
        });

      /*
       * ----------------------------------------------------
       * Create business
       * ----------------------------------------------------
       */
      await Business.create({
        ...data.business,

        ownerId:
          createdUser._id,

        sellerRole:
          data.sellerRole,

        bvnEncrypted,
        ninEncrypted,
        abssinEncrypted,
        cacNumber: data.cacNumber,
        documentDetails: data.documentDetails,
        ninDocument: ninDocument || undefined,
        identityConsentAt: data.verificationConsent ? new Date() : undefined,
        identityChecks: { cac: "pending", abssin: "pending", nin: "pending" },

        bvnLastFour:
          data.bvn.slice(-4),

        cacDocument:
          document,

        verificationStatus:
          "pending",
      });

      return {
        success: true,

        message:
          "Registration submitted. Your identity and business are pending review.",
      };
    } catch (error) {
      /*
       * ====================================================
       * COMPENSATING ROLLBACK
       * ====================================================
       *
       * Since standalone MongoDB cannot run transactions,
       * manually undo anything created during this request.
       */

      /*
       * First determine whether registration may actually
       * have completed.
       */
      const committedUser =
        await User.findOne({
          email,
        }).select(
          "+signupProofHash"
        );

      const committedBusiness =
        committedUser
          ? await Business.findOne({
              ownerId:
                committedUser._id,
            })
          : null;

      /*
       * If both records exist with the same signup proof,
       * signup succeeded. Do NOT delete anything.
       */
      if (
        committedUser
          ?.signupProofHash ===
          proofHash &&
        committedBusiness
      ) {
        return {
          success: true,

          message:
            "Registration already submitted.",
        };
      }

      /*
       * Business was not successfully created.
       *
       * Remove the user created by THIS signup request.
       */
      if (
        createdUser?._id
      ) {
        await User.deleteOne({
          _id:
            createdUser._id,

          signupProofHash:
            proofHash,
        }).catch(
          (cleanupError) => {
            console.error(
              "Signup user cleanup failed:",
              cleanupError
            );
          }
        );
      }

      /*
       * Restore verification token if THIS request
       * successfully consumed it.
       *
       * That allows the frontend to retry the final
       * registration request.
       */
      if (proofConsumed) {
        await Challenge.updateOne(
          {
            email,
            proofHash,
          },
          {
            $unset: {
              usedAt: "",
            },
          }
        ).catch(
          (cleanupError) => {
            console.error(
              "Signup proof restore failed:",
              cleanupError
            );
          }
        );
      }

      /*
       * Delete the uploaded document because registration
       * did not complete.
       */
      await cleanupDocuments();

      /*
       * Preserve normal application errors.
       */
      throw error;
    }
  }

  /**
   * ======================================================
   * REGISTER CUSTOMER
   * ======================================================
   */
  async function registerCustomer(
    body
  ) {
    if (
      body?.role !==
      "customer"
    ) {
      throw new SignupError(
        "Seller signup requires the complete multipart form.",
        415
      );
    }

    const email =
      normalizeEmail(
        body.email
      );

    const password =
      await bcrypt.hash(
        validatePassword(
          body.password
        ),
        12
      );

    await connect();

    /*
     * JSON signup should never be able to overwrite an
     * existing account or choose vendor/admin permissions.
     */
    const existing =
      await User.findOne({
        email,
      });

    if (existing) {
      throw new SignupError(
        "An account with this email already exists. Sign in or resend your verification code.",
        409
      );
    }

    await User.create({
      email,

      password,

      role:
        "customer",

      emailVerified:
        false,
    });

    /*
     * Send verification email after creating customer.
     */
    return sendCode(email);
  }

  /**
   * ======================================================
   * PUBLIC SERVICE METHODS
   * ======================================================
   */
  return {
    sendCode,
    verifyCode,
    registerSeller,
    registerCustomer,
  };
}