
import { Geist, Geist_Mono } from "next/font/google";

import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",Dashboard
//   description: "Generated by create next app",
// };

export default function LayoutDashboard({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}

    >
      <body className="bg-[#F4F4F4] text-black">

        <AuthProvider>

          {children}
        </AuthProvider>

     

      </body>
    </html>
  );
}
